### ISSUE TITLE
Setting LD_LIBRARY_PATH makes jobs fail on DEA nodes.

### ISSUE THREAD

**Issue by simonjohansson** [cloudfoundry-community/bosh-gen#33]
Aloha!

Im using bosh-gen to generate a release/job for a check_mk agent for monitoring purposes of our CF installation. The release works like a charm on all the jobs except the DEAs.

In ctl_setup.sh

```
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH:-''} # default to empty
for package_bin_dir in $(ls -d /var/vcap/packages/*/lib)
do
  export LD_LIBRARY_PATH=${package_bin_dir}:$LD_LIBRARY_PATH
done
```

On a DEA jobs this will cause issues since the VMs have the rootfs_lucid64 package installed.
On a DEA machine LD_LIBRARY_PATH will end up being /var/vcap/packages/ruby/lib:/var/vcap/packages/rootfs_lucid64/lib:/var/vcap/packages/dea_next/lib

Right after we set the LD_LIBRARY_PATH we continue in the ctl_setup script;

```
export RUN_DIR=/var/vcap/sys/run/$JOB_NAME
export LOG_DIR=/var/vcap/sys/log/$JOB_NAME
export TMP_DIR=/var/vcap/sys/tmp/$JOB_NAME
export STORE_DIR=/var/vcap/store/$JOB_NAME
for dir in $RUN_DIR $LOG_DIR $TMP_DIR $STORE_DIR
do
  mkdir -p ${dir}
  chown vcap:vcap ${dir}
  chmod 775 ${dir}
done
export TMPDIR=$TMP_DIR
```

At this point mkdir will fail with a segmentation fault, and thus the bin/JOB_NAME_ctl script used by monit to start the job.

Here are some steps to reproduce the issue (on a DEA node);
```
$ ldd /bin/mkdir
    linux-vdso.so.1 =>  (0x00007fff4f6df000)
    libselinux.so.1 => /lib/x86_64-linux-gnu/libselinux.so.1 (0x00007fc64eff0000)
    libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fc64ec2a000)
    libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007fc64e9eb000)
    libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fc64e7e7000)
    /lib64/ld-linux-x86-64.so.2 (0x00007fc64f21c000)

$ export LD_LIBRARY_PATH=/var/vcap/packages/ruby/lib:/var/vcap/packages/rootfs_lucid64/lib:/var/vcap/packages/dea_next/lib

$ mkdir
mkdir: /var/vcap/packages/rootfs_lucid64/lib/libc.so.6: version `GLIBC_2.14' not found (required by mkdir)

# To fix
$ export LD_LIBRARY_PATH=/lib/x86_64-linux-gnu:/var/vcap/packages/ruby/lib:/var/vcap/packages/rootfs_lucid64/lib:/var/vcap/packages/dea_next/lib

$ mkdir
mkdir: missing operand
Try 'mkdir --help' for more information.
```

Why are we setting the LD_LIBRARY_PATH?

**Comment by drnic** [comment]
@simonjohansson I think its perfectly valid to delete/change stuff in the generated helpers. Its kinda why I generate them for each job template rather than have shared helpers in a package.

Do you have any thoughts on where we should go with the helper scripts?

**Comment by jhunt** [comment]
We have since independently discovered this exact problem with Diego and Concourse, both of which include a rootfs with busybox in them.  We applied a heuristic rule to skip all package directories that contain the `busybox` executable, in 622c06880bd.
