### ISSUE TITLE
Stack trace when attempting `bosh-gen manifest`

### ISSUE THREAD

**Issue by mkb** [cloudfoundry-community/bosh-gen#40]
Without `latest_release_filename` specified in `config/dev.yml`, manifest creation blows up and its not obvious what to do without looking at the source.

    mkb@beemo ~/code/counter-boshrelease [master]
    ± % bosh-gen manifest counter-demo .                                                                  [ruby-2.1.5@bosh]
    /Users/mkb/.rvm/gems/ruby-2.1.5@bosh/gems/bosh-gen-0.18.4/lib/bosh/gen/models/release_detection.rb:12:in `expand_path': no implicit conversion of nil into String (TypeError)
            from /Users/mkb/.rvm/gems/ruby-2.1.5@bosh/gems/bosh-gen-0.18.4/lib/bosh/gen/models/release_detection.rb:12:in `initialize'
            from /Users/mkb/.rvm/gems/ruby-2.1.5@bosh/gems/bosh-gen-0.18.4/lib/bosh/gen/generators/deployment_manifest_generator.rb:55:in `new'
            from /Users/mkb/.rvm/gems/ruby-2.1.5@bosh/gems/bosh-gen-0.18.4/lib/bosh/gen/generators/deployment_manifest_generator.rb:55:in `release_detector'
            from /Users/mkb/.rvm/gems/ruby-2.1.5@bosh/gems/bosh-gen-0.18.4/lib/bosh/gen/generators/deployment_manifest_generator.rb:73:in `detect_jobs'
            from /Users/mkb/.rvm/gems/ruby-2.1.5@bosh/gems/bosh-gen-0.18.4/lib/bosh/gen/generators/deployment_manifest_generator.rb:78:in `jobs'
            from /Users/mkb/.rvm/gems/ruby-2.1.5@bosh/gems/bosh-gen-0.18.4/lib/bosh/gen/generators/deployment_manifest_generator.rb:29:in `check_valid_requested_jobs'
            from /Users/mkb/.rvm/gems/ruby-2.1.5@bosh/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
            from /Users/mkb/.rvm/gems/ruby-2.1.5@bosh/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
            from /Users/mkb/.rvm/gems/ruby-2.1.5@bosh/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
            from /Users/mkb/.rvm/gems/ruby-2.1.5@bosh/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
            from /Users/mkb/.rvm/gems/ruby-2.1.5@bosh/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
            from /Users/mkb/.rvm/gems/ruby-2.1.5@bosh/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
            from /Users/mkb/.rvm/gems/ruby-2.1.5@bosh/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
            from /Users/mkb/.rvm/gems/ruby-2.1.5@bosh/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
            from /Users/mkb/.rvm/gems/ruby-2.1.5@bosh/gems/bosh-gen-0.18.4/lib/bosh/gen/cli.rb:134:in `manifest'
            from /Users/mkb/.rvm/gems/ruby-2.1.5@bosh/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
            from /Users/mkb/.rvm/gems/ruby-2.1.5@bosh/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
            from /Users/mkb/.rvm/gems/ruby-2.1.5@bosh/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
            from /Users/mkb/.rvm/gems/ruby-2.1.5@bosh/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
            from /Users/mkb/.rvm/gems/ruby-2.1.5@bosh/gems/bosh-gen-0.18.4/bin/bosh-gen:7:in `<top (required)>'
            from /Users/mkb/.rvm/gems/ruby-2.1.5@bosh/bin/bosh-gen:23:in `load'
            from /Users/mkb/.rvm/gems/ruby-2.1.5@bosh/bin/bosh-gen:23:in `<main>'
            from /Users/mkb/.rvm/gems/ruby-2.1.5@bosh/bin/ruby_executable_hooks:15:in `eval'
            from /Users/mkb/.rvm/gems/ruby-2.1.5@bosh/bin/ruby_executable_hooks:15:in `<main>'

**Comment by drnic** [comment]
I don't think `bosh-gen manifest` is necessary (nor was it very good if I recall) in the era of spiff templtes; so going to remove it https://github.com/cloudfoundry-community/bosh-gen/pull/57
