### ISSUE TITLE
bosh-lite releases

### ISSUE THREAD

**Issue by ezbercih** [cloudfoundry-community/bosh-gen#42]
Is there a way to generate a bosh-lite release? Old blog posts and video demo mentions it but I cannot figure out how to go about it as I am not sure which of the three options (1. AWS 2. OpenStack 3. vSphere) I am supposed to pick when starting new.

**Comment by drnic** [comment]
Sorry for confusion - The initial prompt isn't for the type of release; it is where the uploaded blobs will be stored so the release can be shared.




The generates scaffold will include some default warden/bosh-lite templates. I use bosh-lite to develop all my releases.

**Comment by ezbercih** [comment]
I see.. what if I don't plan on sharing it and just experimenting? I don't have a vSphere or OpenStack instance and I don't want to push it to S3.. is there any way to bypass this step?

**Comment by drnic** [comment]
Pushing anything is optional. It's just going to create a bucket for you in advance & setup config/private.yml and config/final.yml correctly.




If you choose to "bosh upload blobs" or "bosh create release --final" that's a choice for later. The bucket will stay empty until then.




Sorry I don't yet have a way to delay setup of the blob store.

**Comment by ezbercih** [comment]
Thanks! It's not a showstopper so I'm closing this.
