### ISSUE TITLE
Tutorial outdated?

### ISSUE THREAD

**Issue by ezbercih** [cloudfoundry-community/bosh-gen#43]
I am trying to follow the steps on the tutorial provided in README for setting up a cassandra release however I get stuck at the following step:

bosh-gen extract-pkg ../cf-release/packages/dea_jvm7

There is not directory called dea_jvm7. Could it be called something else?

**Comment by drnic** [comment]
Sorry, that commit didn't include a fix for the tutorial. Looking at a new tutorial now.

**Comment by jhunt** [comment]
Tutorial seems to have been updated to extract postgres.  Can this be closed?
