### ISSUE TITLE
Feedback: packages created from "apt" are hard to use

### ISSUE THREAD

**Issue by cyrille-leclerc** [cloudfoundry-community/bosh-gen#46]
I use a "GitHub issue" to share this experience: we were very interested in the "apt"  approach for packages but it tends to be very hard to use when the installed package define configuration file under `/etc/`...

For example, we wanted to use the `apt` approach to install 'fontconfig' and 'ttf-dejavu' for OpenJDK8 and we switched back to the approach based on source code and compilation.

For example, the `fc-cache` tool of 'fontconfig' did not want to work under `/var/vcap/packages/fontconfig/apt/...`:

* couldn't find the required '.so', we had to play with `LD_LIBRARY_PATH`
* couldn't find a config file expected under '/etc/...', the param `sysroot` did not help so I gave up and switched back from apt to src+compilation

As a conclusion, I am convinced that installing native packages with apt is the right way to go but these packages should be installed under their default folder tree and I guess we will have to wait for a docker style approach to do it.

**Comment by drnic** [comment]
Yep trying to bring apt packages into bosh land isn't pretty and hasn't worked for me for all cases.




I don't have a better solution I'm sorry. This issue is a reality of bosh packages being more like rvm, homebrew packages than old school Unix distro packages.




My suggestion for you is to use docker to package up everything and pull that in.

**Comment by cyrille-leclerc** [comment]
Thanks for the suggestion. 

> This issue is a reality of bosh packages being more like rvm, homebrew packages than old school Unix distro packages.

I had a similar feeling. I pretty quickly discovered that I prefered to install "old school distro packages".

> My suggestion for you is to use docker to package up everything and pull that in.

We have an important codebase to build a pivotal product. We will probably wait for the best practices of Docker for Cloud Foundry get more mature.

I see a lot of activity on Docker for Cloud Foundry and I hope that BOSH will soon evolve a lot.

**Comment by cppforlife** [comment]
Yeah, we have yet to agree on an approach of how to best use Docker images with BOSH. 

It's possible and some people do it; however, there are few interesting nuances. One of them is stemcell vs Docker image contents: we typically want to be able to update the stemcell which includes some basic packages and hardened configuration, and for the releases to not have to change; however, if Docker image is introduced as part of some BOSH job (let's say a regular image, Ubuntu based) suddenly that job is running in the environment that someone has to care about more carefully i.e. review all packages image includes, look for unwanted configurations in that image, etc.
