### ISSUE TITLE
bosh-gem new error

### ISSUE THREAD

**Issue by ezhang-pivotal** [cloudfoundry-community/bosh-gen#62]
Error when new, the same of AWS or OpenStack or vSphere:
vagrant@bosh-lite:~$ bosh-gen new test
      create
1. AWS
2. OpenStack
3. vSphere
Choose your infrastructure: 3

Using provider vSphere

Username: 1
Password: 1
Server: 1
/var/lib/gems/1.9.1/gems/cyoi-0.11.3/lib/cyoi/cli/providers/provider_cli_vsphere.rb:22:in `setup_credentials': undefined local variable or method`h1' for #Cyoi::Cli::Providers::ProviderCliVsphere:0x0000000182ce58 (NameError)
    from /var/lib/gems/1.9.1/gems/cyoi-0.11.3/lib/cyoi/cli/providers/provider_cli_vsphere.rb:6:in `perform_and_return_attributes'
    from /var/lib/gems/1.9.1/gems/cyoi-0.11.3/lib/cyoi/cli/provider.rb:18:in`execute!'
    from /var/lib/gems/1.9.1/gems/bosh-gen-0.20.1/lib/bosh/gen/generators/new_release_generator.rb:28:in `select_provider'
    from /usr/lib/ruby/vendor_ruby/thor/command.rb:27:in`run'
    from /usr/lib/ruby/vendor_ruby/thor/invocation.rb:121:in `invoke_command'
    from /usr/lib/ruby/vendor_ruby/thor/invocation.rb:128:in`block in invoke_all'
    from /usr/lib/ruby/vendor_ruby/thor/invocation.rb:128:in `each'
    from /usr/lib/ruby/vendor_ruby/thor/invocation.rb:128:in`map'
    from /usr/lib/ruby/vendor_ruby/thor/invocation.rb:128:in `invoke_all'
    from /usr/lib/ruby/vendor_ruby/thor/group.rb:232:in`dispatch'
    from /usr/lib/ruby/vendor_ruby/thor/base.rb:440:in `start'
    from /var/lib/gems/1.9.1/gems/bosh-gen-0.20.1/lib/bosh/gen/cli.rb:18:in`new'
    from /usr/lib/ruby/vendor_ruby/thor/command.rb:27:in `run'
    from /usr/lib/ruby/vendor_ruby/thor/invocation.rb:121:in`invoke_command'
    from /usr/lib/ruby/vendor_ruby/thor.rb:363:in `dispatch'
    from /usr/lib/ruby/vendor_ruby/thor/base.rb:440:in`start'
    from /var/lib/gems/1.9.1/gems/bosh-gen-0.20.1/bin/bosh-gen:7:in `<top (required)>'
    from /usr/local/bin/bosh-gen:23:in`load'
    from /usr/local/bin/bosh-gen:23:in `<main>'

ruby version: ruby 1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]

ruby gem list:
gem list

**\* LOCAL GEMS ***

activesupport (4.2.1)
aws-sdk (1.60.2)
aws-sdk-v1 (1.60.2)
blobstore_client (1.2983.0, 1.2820.0)
bosh-gen (0.20.1)
bosh-template (1.2983.0, 1.2820.0)
bosh_cli (1.2820.0)
bosh_common (1.2983.0, 1.2820.0)
builder (3.2.2)
bundler (1.3.5)
cf-message-bus (0.3.1)
cf-registrar (1.0.3)
cf-uaa-lib (3.2.1)
CFPropertyList (2.3.1)
cyoi (0.11.3)
daemons (1.1.9)
eventmachine (1.0.3)
excon (0.45.3, 0.43.0)
fission (0.5.0)
fluent-logger (0.4.9)
fog (1.27.0, 1.23.0)
fog-atmos (0.1.0)
fog-aws (0.1.1)
fog-brightbox (0.7.1)
fog-core (1.30.0, 1.27.3)
fog-ecloud (0.1.3)
fog-google (0.0.5)
fog-json (1.0.0)
fog-local (0.2.1)
fog-powerdns (0.1.1)
fog-profitbricks (0.0.3)
fog-radosgw (0.0.4)
fog-riakcs (0.1.0)
fog-sakuracloud (1.0.1)
fog-serverlove (0.1.2)
fog-softlayer (0.3.30)
fog-storm_on_demand (0.1.1)
fog-terremark (0.1.0)
fog-vmfusion (0.1.0)
fog-voxel (0.1.0)
fog-xml (0.1.2)
formatador (0.2.5)
highline (1.6.21)
httpclient (2.4.0)
i18n (0.7.0)
inflecto (0.0.2)
ipaddress (0.8.0)
json (1.8.2)
json_pure (1.8.2, 1.8.1)
little-plugger (1.1.3)
log4r (1.1.10)
logging (1.8.2)
mime-types (2.4.3)
mini_portile (0.6.2)
minitar (0.5.4)
minitest (5.7.0)
msgpack (0.5.9)
multi_json (1.10.1)
nats (0.5.0.beta.16, 0.5.0.beta.14)
net-http-persistent (2.9)
net-scp (1.1.2)
net-ssh (2.9.2)
net-ssh-gateway (1.2.0)
netaddr (1.5.0)
nokogiri (1.6.6.1)
progressbar (0.9.2)
rack (1.5.2)
rdoc (3.9.4)
readwritesettings (3.0.1)
ruby-atmos-pure (1.0.5)
ruby-hmac (0.4.0)
semi_semantic (1.1.0)
steno (1.2.4)
terminal-table (1.4.5)
thin (1.6.3, 1.6.2)
thor (0.18.1.20140116)
thread_safe (0.3.5)
tzinfo (1.2.2)
vcap-concurrency (0.1.0)
yajl-ruby (1.2.1)

**Comment by drnic** [comment]
Ah vsphere - I haven't ever used that section of code personally; I'm sorry if I introduced a regression when changing/refactoring other parts of the code base.

**Comment by ezhang-pivotal** [comment]
Hi Dr @drnic ，do you know how to generate package SHA1 fingerprint?

**Comment by drnic** [comment]
Bosh should generate all fingerprints etc when you use "bosh upload blobs" and "bosh create release --final"

**Comment by ezhang-pivotal** [comment]
I'd like to use existed release. and want to add one small package. I think I maybe can just add a section in release.MF

**Comment by drnic** [comment]
The command should still just work to import the files; and then still use bosh commands above to build release.

**Comment by nctiggy** [comment]
I too am getting the original posted error for vSphere. exhang, did you ever find a work around? drnic, should I just use a different provider and swap out the vSphere data in the settings.yml afterward?

**Comment by drnic** [comment]
Yeah that sounds like the workaround for the moment. I need a way to tell cyoi library not to show vsphere. The goal is to enter s3 blob store credentials and create/setup the blobstore
