### ISSUE TITLE
source helper/ctl_setup hangs on redirect_output ${output_label}

### ISSUE THREAD

**Issue by ramonskie** [cloudfoundry-community/bosh-gen#63]
it seems that the redirect_output ${output_label} functions hangs
when i manually source this file bash hangs

https://github.com/cloudfoundry-community/bosh-gen/blob/master/lib/bosh/gen/generators/job_generator/templates/jobs/%25job_name%25_simple/templates/helpers/ctl_setup.sh#L28

**Comment by drnic** [comment]
Hmm I can't think of a reason you might get this behavior. Ideas?

**Comment by ramonskie** [comment]
no clue at all
i have commented it out for now
