### ISSUE TITLE
ctl_setup - auto load from job's packages only

### ISSUE THREAD

**Issue by drnic** [cloudfoundry-community/bosh-gen#66]
Instead of https://github.com/cloudfoundry-community/bosh-gen/blob/e547126a3e9eb0f3dd9095f1fecd6935eac8b8f1/lib/bosh/gen/generators/job_generator/templates/jobs/%25job_name%25_nginx_rack/templates/bin/ctl_setup.sh.erb#L29-L32 which loads from global set of packages from across all colocated jobs, look up from the job's packages only `/var/vcap/jobs/<myjob>/packages/*`

**Comment by frodenas** [comment]
I was thinking to use the same trick on my helpers, but unfortunately `/var/vcap/jobs/<myjob>/packages/*` contains not just the job's packages but **all** packages.

**Comment by drnic** [comment]
Perhaps we need to fix BOSH then at the same time

**Comment by frodenas** [comment]
:pray:

**Comment by vito** [comment]
:(

come to think of it that's also not necessarily safe (but it's at least better). if I were to do that with my own packages that depend on the rootfses I'll still get really weird behavior.

**Comment by drnic** [comment]
@cppforlife any ideas/proposals for how a job template can programmatically setup `$PATH`, etc for each of its packages?
