### ISSUE TITLE
Cannot install latest bosh-gen

### ISSUE THREAD

**Issue by jacopen** [cloudfoundry-community/bosh-gen#69]
I tried to install latest bosh-gen but it failed.

```
gem install bosh-gen -v 0.21.1 --no-ri --no-rdoc
ERROR:  While executing gem ... (Gem::DependencyResolutionError)
    conflicting dependencies fog (~> 1.34.0) and fog (~> 1.11)
  Activated fog-1.11.0
  which does not match conflicting dependency (~> 1.34.0)

  Conflicting dependency chains:
    bosh-gen (= 0.21.1), 0.21.1 activated, depends on
    fog (~> 1.11), 1.11.0 activated

  versus:
    bosh-gen (= 0.21.1), 0.21.1 activated, depends on
    bosh_cli (>= 0), 1.3104.0 activated, depends on
    blobstore_client (~> 1.3104.0), 1.3104.0 activated, depends on
    fog (~> 1.34.0)
```

It seems current version of blobstore_client requires fog '~>1.34.0' but bosh-gen requires '~> 1.11'
https://github.com/cloudfoundry/bosh/blob/master/blobstore_client/blobstore_client.gemspec#L24

As a workaround, install a bit older version of bosh_cli(1.3094.0) at first and it successfully installed.

```
$ gem install bosh_cli -v 1.3094.0 --no-ri --no-rdoc
$ gem install bosh-gen -v 0.21.1 --no-ri --no-rdoc
```

**Comment by ssdowd** [comment]
I also had issues with having bosh_cli (1.3104.0) and bosh-gen (latest) installed.

```
Failed to load plugin /Library/Ruby/Gems/2.0.0/gems/bosh-gen-0.21.1/lib/bosh/cli/commands/share_release.rb: Unable to activate bosh-gen-0.21.1, because fog-aws-0.7.6 conflicts with fog-aws (= 0.1.1)
```

**Comment by drnic** [comment]
I wonder why bosh is now being very specific about fog version?




Perhaps bosh-gen can remove all ~> for a version and just assume you have a new enough fog version?

**Comment by drnic** [comment]
I'm personally seeing the latter issue:

```
Failed to load plugin /Users/drnic/.rvm/gems/ruby-2.2.1/gems/bosh-gen-0.20.1/lib/bosh/cli/commands/share_release.rb: Unable to activate bosh-gen-0.20.1, because fog-aws-0.7.6 conflicts with fog-aws (= 0.1.1)
```

Will investigate.

**Comment by ssdowd** [comment]
I suspect this is due to an underlying ruby version mismatch.  I just updated to 2.3.0 via rbenv and bosh-gen installed cleanly.  Prior to that I was using 1) the native OSX ruby and 2) 2.1.8.  Install failed with each of those.

**Comment by poblin-orange** [comment]
tested ok with rvm ruby 2.3.0

**Comment by 7hunderbird** [comment]
@jacopen Have you tried this again with a more up-to-date version of ruby?  Just checking in.  Thanks!
