### ISSUE TITLE
make_manifest incorrectly detects CPI on bosh-lite

### ISSUE THREAD

**Issue by mkuratczyk** [cloudfoundry-community/bosh-gen#70]
Hi,

I'm working on a release that requires a CentoOS stemcell. When I set STEMCELL_OS=centos make_manifest fails because it can't find an appropriate stemcell. If I'm not wrong the root cause of this issue is here:
https://github.com/cloudfoundry-community/bosh-gen/blob/602fcabfe235a5f8759cfb37b887065562075036/lib/bosh/gen/generators/new_release_generator/templates/templates/make_manifest.tt#L20

It expects 'bosh status' to return CPI=warden while at least on my environment there is 'cpi' there:
Director
  Name       Bosh Lite Director
  URL        https://192.168.50.4:25555
  Version    1.3074.0 (00000000)
  User       admin
  UUID       9bca5701-66c0-43ee-a4d0-64813b4b5ece
  CPI        cpi
  dns        disabled
  compiled_package_cache enabled (provider: local)
  snapshots  disabled

When I manually set DIRECTOR_CPI=warden everything works well and the right stemcell is uploaded.

Thanks,

**Comment by jhunt** [comment]
Have you tried upgrading your vagrant box?  My BOSH-lite, v1.3126.0 reports the CPI as warden_cpi, and latest builds of bosh-gen handle that:

https://github.com/cloudfoundry-community/bosh-gen/blob/master/lib/bosh/gen/generators/new_release_generator/templates/templates/make_manifest.tt#L33
