### ISSUE TITLE
wait_pid() kills just to root process not its childs as well

### ISSUE THREAD

**Issue by milkotodorov** [cloudfoundry-community/bosh-gen#85]
Hello,

the wait_pid() function in the ctl_utils.sh is killing just to root process and not the processes started by it. In case the starting script start another script with on its turn starts another and so on, stopping of the root process would not stop all the child processes.

It would be nice if this is extended so the whole tree is killed.

Regards,
Milko

**Comment by drnic** [comment]
@milkotodorov sorry for not seeing this issue til now; do you have any suggestions for how the processes should be cleanly handled?

**Comment by jhunt** [comment]
Short of pulling the whole subtree of pids via some ps+grep hackery, I don't know of anyway to do this outside of C (or any language with ready access to both `/proc` and the raw system calls behind the `kill` / `killall` utilities).

Ideally, the root process would, upon receiving SIGTERM, turn around and kill its children, who would in turn kill their children, etc, etc.

**Comment by milkotodorov** [comment]
@drnic ideally killing the root process should kill it's children too.
Since we can find the children of a process we can iterate recursively and kill them all.
In this state all clild processes won't be terminated.

**Comment by drnic** [comment]
@milkotodorov do you have some code that works for you in other places that you'd like to see in all bosh releases?

**Comment by jhunt** [comment]
Typically that's why you should `exec` from the bash script after storing the process ID, then the Java process _is_ the old script process, with the correct PID.

**Comment by jhunt** [comment]
@milkotodorov were you able to test if using `exec` works for you in this scenario?

**Comment by milkotodorov** [comment]
yes - it worked. Thanks

**Comment by drnic** [comment]
Related to this topic: I am exploring the new https://github.com/cloudfoundry-incubator/bpm-release/ for wrapping job processes inside containers; it will mean we get rid of all our wrapper scripts.

WIP PR at https://github.com/cloudfoundry-community/bosh-gen/pull/102
