### ISSUE TITLE
Trying to install bosh-gen get missing fog-aws 0.1.1, can't gem install it.

### ISSUE THREAD

**Issue by haydonryan** [cloudfoundry-community/bosh-gen#88]
fog-aws (0.12.0)

```
$ gem install bosh-gen
ERROR:  While executing gem ... (Gem::DependencyError)
    Unable to resolve dependencies: bosh-gen requires fog-aws (= 0.1.1)

$ sudo gem install fog-aws 0.1.1
Successfully installed fog-aws-0.12.0
ERROR:  Could not find a valid gem '0.1.1' (>= 0) in any repository
```

**Comment by drnic** [comment]
Oh joy :)
Afai remember, fog-aws 0.1.2 was bad; we can probably loosen the fog-aws restriction. If you'd like to try it out via source code and submit a PR, I'll be indebted to you with a high five in future.






On Thu, Nov 17, 2016 at 5:26 AM +1000, "Haydon Ryan" <notifications@github.com> wrote:












fog-aws (0.12.0)
$ gem install bosh-gen
ERROR:  While executing gem ... (Gem::DependencyError)
    Unable to resolve dependencies: bosh-gen requires fog-aws (= 0.1.1)

$ sudo gem install fog-aws 0.1.1
Successfully installed fog-aws-0.12.0
ERROR:  Could not find a valid gem '0.1.1' (>= 0) in any repository

**Comment by haydonryan** [comment]
Looks like it's linked to the ruby version. changing to 2.1.1, worked fine. but using the osx system it wasn't happy.
